<HomeScreen>

	canvas:
		Color:
			rgb: 0.13725, 0.12157, 0.12549
		Rectangle:
            pos: self.pos
            size: self.size

	name: app.get_string('Home_Screen')

	BoxLayout:
		id: hSBoxLayout
		orientation: 'horizontal'

		Label:
			id: hSMainLabel
			text: app.get_string('Home_Screen_Intro_Text')
			size_hint: (.735, 1)

		AsyncImage:
			id: hSImage
			source: 'res/images/HomePageImage.png'
			size_hint: (.265, 1)
			allow_stretch: True
			keep_ratio:False
